In [4]:
"""
某电商平台的用户行为数据如下，请完成以下任务
1.计算每位用户的总消费金额（消费金额 = 商品单价 * 购买数量）
2.找出消费金额最高的用户，并输出其所有信息
3.计算所有用户的平均消费金额（保留2位小数）
4.统计电子产品的总购买数量
"""
import pandas as pd
data = {
    '用户id':[101,102,103,104,105],
    '用户名':['Alice','Bob','Charlie','David','Eve'],
    '商品类别':['电子产品','服饰','电子产品','家具','服饰'],
    '商品单价':[1200,300,800,150,200],
    '购买数量':[1,3,2,5,4]
}
df = pd.DataFrame(data)
df

   用户id      用户名  商品类别  商品单价  购买数量
0   101    Alice  电子产品  1200     1
1   102      Bob    服饰   300     3
2   103  Charlie  电子产品   800     2
3   104    David    家具   150     5
4   105      Eve    服饰   200     4

In [5]:
df['总消费金额'] = df['商品单价'] * df['购买数量']
df

   用户id      用户名  商品类别  商品单价  购买数量  总消费金额
0   101    Alice  电子产品  1200     1   1200
1   102      Bob    服饰   300     3    900
2   103  Charlie  电子产品   800     2   1600
3   104    David    家具   150     5    750
4   105      Eve    服饰   200     4    800

In [6]:
df.nlargest(1,columns=['总消费金额'])

   用户id      用户名  商品类别  商品单价  购买数量  总消费金额
2   103  Charlie  电子产品   800     2   1600

In [7]:
df['总消费金额'].mean()

np.float64(1050.0)

In [8]:
df[df['商品类别'] == '电子产品']['购买数量'].sum()

np.int64(3)