In [4]:
import pandas as pd
data = {
    'ID':[1,2],
    'name':['alice','bob'],
    'Math':[90,85],
    'English':[88,92],
    'History':[95,89]
}

df = pd.DataFrame(data)
df.T
df

   ID   name  Math  English  History
0   1  alice    90       88       95
1   2    bob    85       92       89

In [6]:
# 宽表转换成长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values('name')

   ID   name       科目  分数
0   1  alice     Math  90
2   1  alice  English  88
4   1  alice  History  95
1   2    bob     Math  85
3   2    bob  English  92
5   2    bob  History  89

In [7]:
# 长表转宽表
pd.pivot(df2,index=['ID','name'],columns='科目',values='分数')

科目        English  History  Math
ID name
1  alice       88       95    90
2  bob         92       89    85

In [12]:
data = {
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'Math':[90,85],
    'English':[88,92],
    'History':[95,89]
}

df = pd.DataFrame(data)
# 分列
df[['first','last']] = df['name'].str.split(" ",expand=True)
df

   ID         name  Math  English  History  first   last
0   1  alice smith    90       88       95  alice  smith
1   2    bob smith    85       92       89    bob  smith