In [1]:
# 数据分箱 pd.cut(x,bins,labels)
import pandas as pd

df = pd.read_csv('employees.csv')
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [5]:
df1 = df.head(10)[['employee_id','salary']]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [7]:
print(df1['salary'].head(10))
pd.cut(df1['salary'].head(10),bins=2)

0    24000.0
1    17000.0
2    17000.0
3     9000.0
4     6000.0
5     4800.0
6     4800.0
7     4200.0
8    12000.0
9     9000.0
Name: salary, dtype: float64

0    (14100.0, 24000.0]
1    (14100.0, 24000.0]
2    (14100.0, 24000.0]
3     (4180.2, 14100.0]
4     (4180.2, 14100.0]
5     (4180.2, 14100.0]
6     (4180.2, 14100.0]
7     (4180.2, 14100.0]
8     (4180.2, 14100.0]
9     (4180.2, 14100.0]
Name: salary, dtype: category
Categories (2, interval[float64, right]): [(4180.2, 14100.0] < (14100.0, 24000.0]]

In [8]:
pd.cut(df1['salary'].head(10),bins=2).value_counts()

salary
(4180.2, 14100.0]     7
(14100.0, 24000.0]    3
Name: count, dtype: int64

In [11]:
df1['收入范围'] = pd.cut(df1['salary'].head(10),bins=[0,10000,20000,30000],labels=['低','中','高'])

In [17]:
df1

   employee_id   salary 收入范围
0          100  24000.0    高
1          101  17000.0    中
2          102  17000.0    中
3          103   9000.0    低
4          104   6000.0    低
5          105   4800.0    低
6          106   4800.0    低
7          107   4200.0    低
8          108  12000.0    中
9          109   9000.0    低

In [19]:
pd.qcut(df1['salary'],3).value_counts()

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [21]:
# 睡眠数据
df = pd.read_csv('sleep.csv')
df1 = df.head(10)[['person_id','sleep_quality']]
df1

   person_id  sleep_quality
0          1            7.0
1          2            4.9
2          3            6.0
3          4           10.0
4          5            9.5
5          6            6.9
6          7            6.1
7          8            6.2
8          9            7.2
9         10            4.0

In [32]:
# 数值->分箱->统计
df['睡眠质量'] = pd.cut(df['sleep_quality'],bins=3,labels=['差','中','优'])
print(df['睡眠质量'].value_counts())
# 字符串->类别->统计
df['gender'] = df['gender'].astype('category')
print(df['gender'].value_counts())

print(df['睡眠质量'].dtypes)
print(df['gender'].dtypes)

睡眠质量
中    206
优    129
差     65
Name: count, dtype: int64
gender
Female    201
Male      199
Name: count, dtype: int64
category
category

In [49]:
# df.rename() 给列或索引改名字（不改数据位置）
# df.set_inex() 把列"提升"为行索引，让数据更好查
# df.reset_inex() 把行索引"降级"为普通列，回到默认状态

df = pd.DataFrame({
    'name':['jack','alice','tom','bob'],
    'age':[18,19,20,21],
    'gender':['male','female','male','female'],
})

df.set_index('name',inplace=True)
print(df)
print(df.loc['jack','age'])
df.reset_index('name',inplace=True)
print(df)
df.rename(columns={'age':'年龄'},index={0:4})

       age  gender
name
jack    18    male
alice   19  female
tom     20    male
bob     21  female
18
    name  age  gender
0   jack   18    male
1  alice   19  female
2    tom   20    male
3    bob   21  female

    name  年龄  gender
4   jack  18    male
1  alice  19  female
2    tom  20    male
3    bob  21  female

In [44]:
df.index = [1,2,3,4]
df

    name  age  gender
1   jack   18    male
2  alice   19  female
3    tom   20    male
4    bob   21  female