In [4]:
# 分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数()

import pandas as pd
df = pd.read_csv('employees.csv')
df.dropna(subset=['department_id'], inplace=True)
df['department_id'] = df['department_id'].astype('int64')
df

1
0

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110

In [23]:
# 计算不同部门的平均工资
# print(df.groupby('department_id').groups) # 查看分组
# print(df.groupby('department_id').get_group(10)) # 查看具体的某个分组数据
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
df2.reset_index(inplace=True)
df2.sort_values('salary',ascending=False,inplace=True)
df2

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [29]:
# 计算不同部门不同岗位
df2 = df.groupby(['department_id','job_id'])['salary'].mean()
df2 = df2.reset_index()
df2['salary'] = df2['salary'].round(1)
df2

    department_id      job_id   salary
0              10     AD_ASST   4400.0
1              20      MK_MAN  13000.0
2              20      MK_REP   6000.0
3              30    PU_CLERK   2780.0
4              30      PU_MAN  11000.0
5              40      HR_REP   6500.0
6              50    SH_CLERK   3215.0
7              50    ST_CLERK   2785.0
8              50      ST_MAN   7280.0
9              60     IT_PROG   5760.0
10             70      PR_REP  10000.0
11             80      SA_MAN  12200.0
12             80      SA_REP   8396.6
13             90     AD_PRES  24000.0
14             90       AD_VP  17000.0
15            100  FI_ACCOUNT   7920.0
16            100      FI_MGR  12000.0
17            110  AC_ACCOUNT   8300.0
18            110      AC_MGR  12000.0